### ISSUE TITLE
Last step is misreported as failure step

### ISSUE THREAD

**Issue by max-sixty** [stealthybox/container-builder-github-ci-status#5]
If there are multiple steps running when a failure occurs, the latest task to start is reported as the failure reason, rather than the task with `status=FAILURE`

![image](https://user-images.githubusercontent.com/5635139/39158727-bbb347a2-472f-11e8-87d0-1a41edaefa17.png)

In the report from `cloud container builds describe`, `isort` has a (very slightly!) later start time:
```
  id: run-tests
  status: FAILURE
  timing:
    endTime: '2018-04-22T18:51:47.129276336Z'
    startTime: '2018-04-22T18:41:13.672572721Z'
[...]
  id: isort
  status: SUCCESS
  timing:
    endTime: '2018-04-22T18:41:28.186709447Z'
    startTime: '2018-04-22T18:41:13.672967786Z'
```
